---
#########################################
#            _             _ _          #
#           | |           (_) |         #
#           | | __ ___   ___| | __      #
#       _   | |/ _` \ \ / / | |/ /      #
#      | |__| | (_| |\ V /| |   <       #
#       \____/ \__,_| \_/ |_|_|\_\      #
#                                       #
#########################################

- name: Install OpenSSH
  ansible.builtin.apt:
    name: openssh-server
    state: present
  tags:
    - ssh
    - openssh
    - security
    - hardening
    - system

- name: Configure OpenSSH
  ansible.builtin.copy:
    src: ./templates/sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0644'
  notify: Restart OpenSSH
  tags:
    - ssh
    - openssh
    - security
    - hardening
    - system
